// print.js — Phase 8
(function(){
  function getField(o,paths){ for(const p of paths){ const parts=p.split('.'); let cur=o; for(const k of parts){ if(cur&&k in cur) cur=cur[k]; else { cur=undefined; break; } } if(cur!=null&&cur!=='') return cur; } return null; }
  function parseMD(s){ if(!s) return null; const m=String(s).trim(); const md = m.match(/^(\d{4})-(\d{2})-(\d{2})$/) || m.match(/^(\d{2})-(\d{2})$/); if(!md) return null; const month = md.length===4? parseInt(md[2],10): parseInt(md[1],10); const day = md.length===4? parseInt(md[3],10): parseInt(md[2],10); if(month<1||month>12||day<1||day>31) return null; return {month,day}; }
  function nextOcc(md,t){ const y=t.getFullYear(); const d=new Date(y,md.month-1,md.day); return (d < new Date(t.getFullYear(),t.getMonth(),t.getDate())) ? new Date(y+1,md.month-1,md.day) : d; }
  function within(d,mode){ const t=new Date(); if(mode==='month'){ return d.getFullYear()===t.getFullYear() && d.getMonth()===t.getMonth(); } if(mode==='next30'){ return (d - t)/(1000*60*60*24) <= 30.0001 && (d-t)>=0; } return true; }
  function fullName(c){ return [c.first||'',c.last||''].filter(Boolean).join(' ').trim(); }
  function addrLines(c){ const a1=c.address||''; const a2=[c.city||'', c.state||'', c.zip||''].filter(Boolean).join(', '); return [a1,a2].filter(x=>x && x.trim().length>0); }
  async function renderPrint(){ const view=document.getElementById('view-print'); if(!view||!view.classList||view.classList.contains('hidden')) return; await openDB(); const contacts=await dbGetAll('contacts'); const type=document.getElementById('print-type')?.value || 'birthdays'; const range=document.getElementById('print-range')?.value || 'month'; const cols=parseInt(document.getElementById('print-cols')?.value,10)||3; const today=new Date(); const rows=[]; for(const c of contacts){ const addr=addrLines(c); if(!addr.length) continue; const b=getField(c,['birthday','extras.birthday']); const a=getField(c,['anniversary','extras.anniversary']); const wantB=(type==='birthdays'||type==='both'); const wantA=(type==='anniversaries'||type==='both'); if(wantB && b){ const md=parseMD(b); if(md){ const d=nextOcc(md,today); if(within(d,range)) rows.push({kind:'Birthday',date:d,md,contact:c,addr}); } } if(wantA && a){ const md=parseMD(a); if(md){ const d=nextOcc(md,today); if(within(d,range)) rows.push({kind:'Anniversary',date:d,md,contact:c,addr}); } } } rows.sort((x,y)=> x.date - y.date || fullName(x.contact).localeCompare(fullName(y.contact))); const grid=document.getElementById('print-area'); const summary=document.getElementById('print-summary'); const emptyMsg = 'No eligible contacts yet. Add a mailing address or widen the range.'; if(grid) grid.className='print-grid cols-'+cols; if(summary) summary.textContent = rows.length? `${rows.length} card(s) generated` : emptyMsg; if(grid) grid.innerHTML = rows.length ? rows.map(r=>{ const c=r.contact; const lines=[`<div class="print-card-kind">${r.kind}</div>`,`<div class="print-card-name">${fullName(c)}</div>`,`<div class="print-card-date">${String(new Date(2000,r.md.month-1,r.md.day)).split(' ').slice(1,3).join(' ')}</div>`]; if(r.addr.length) lines.push(`<div class="print-card-addr">${r.addr.map(x=>x.replace(/&/g,'&amp;').replace(/</g,'&lt;')).join('<br>')}</div>`); return `<div class="print-card">${lines.join('')}</div>`; }).join('') : `<div class="print-empty muted">${emptyMsg}</div>`; }
  function wire(){ ['#btn-print-generate','#print-type','#print-range','#print-cols'].forEach(sel=>{ const el=document.querySelector(sel); if(!el || el.__wired) return; el.__wired=true; el.addEventListener('click', renderPrint); el.addEventListener('change', renderPrint); }); const pr=document.getElementById('btn-print'); if(pr && !pr.__wired){ pr.__wired=true; pr.addEventListener('click', ()=> window.print()); } const open=document.getElementById('btn-print-cards'); if(open && !open.__wired){ open.__wired=true; open.addEventListener('click', (e)=>{ e.preventDefault(); if(typeof window.goto === 'function'){ window.goto('#/print'); } else { window.location.hash = '#/print'; } }); } }
  function patch(){ const orig=window.renderAll; if(!orig || orig.__wrappedPrint) return false; const wrap = async function(){ await orig(); wire(); await renderPrint(); }; wrap.__wrappedPrint=true; window.renderAll = wrap; return true; }
  function ensurePatch(){ patch(); wire(); renderPrint(); if(!window.renderPrintCards){ window.renderPrintCards = renderPrint; } if(window.RenderGuard && typeof window.RenderGuard.registerHook === 'function'){ window.RenderGuard.registerHook(patch); if(!ensurePatch.__printHook){ ensurePatch.__printHook = () => { const view=document.getElementById('view-print'); if(view && view.classList && !view.classList.contains('hidden')) renderPrint(); }; window.RenderGuard.registerHook(ensurePatch.__printHook); } } }
  if(document.readyState === 'loading'){
    document.addEventListener('DOMContentLoaded', ensurePatch);
  } else {
    ensurePatch();
  }
})();
