/* Manifest with relative paths (relative to crm-app/js). Dedupe and phase separation. */
import { normalizeModuleId, isSafeMode } from './boot_hardener.js';
export const CORE = [
  './env.js',
  './db.js',
  './core/renderGuard.js',
  './services/selection.js',
  './utils.js',
  './render.js',
  './db_compat.js',
  './ical.js',
  './presets.js',
  '../seed_data_inline.js',
  './seed_data.js',
  './ui_shims.js',
  './header_ui.js',
  './add_contact.js',
  './email/merge_vars.js',
  './contact_stage_tracker.js',
  './commissions.js',
  './post_funding.js',
  './qa.js',
  './bulk_log.js',
  './print.js',
  './app.js',
  './settings_forms.js',
  './services/pipelineStages.js',
  './services/softDelete.js',
  './pipeline/stages.js',
  './pages/workbench.js',
  './pages/email_templates.js',
  './pages/notifications.js',
  './boot/contracts/services.js',
  './boot/phases.js'
];

export const PATCHES = [
  './patch_20250923_baseline.js',
  './patch_20250924_bootstrap_ready.js',
  './patch_20250926_ctc_actionbar.js',
  './patch_2025-09-26_phase1_pipeline_partners.js',
  './patch_2025-09-26_phase2_automations.js',
  './patch_2025-09-26_phase3_dashboard_reports.js',
  './patch_2025-09-26_phase4_polish_regression.js',
  './patch_2025-09-27_doccenter2.js',
  './patch_2025-09-27_contact_linking_5A.js',
  './patch_2025-09-27_contact_linking_5B.js',
  './patch_2025-09-27_contact_linking_5C.js',
  './patch_2025-09-27_merge_ui.js',
  './patch_2025-09-27_phase6_polish_telemetry.js',
  './patch_2025-09-27_nth_bundle_and_qa.js',
  './patch_2025-09-27_masterfix.js',
  './patches/polish_overlay_ready.js',
  './patch_2025-09-27_release_prep.js',
  './patch_2025-10-02_baseline_ux_cleanup.js',
  './patch_2025-10-02_medium_nice.js',
  './patch_2025-10-03_calendar_ics_button.js',
  './patch_2025-10-03_quick_add_partner.js',
  './patch_2025-10-03_automation_seed.js',
  './patches/patch_2025-10-23_dashboard_drag.js',
  './contacts_merge.js',
  './contacts_merge_orchestrator.js',
  './pipeline/kanban_dnd.js',
  './patches/patch_2025-10-23_session_beacon.js',
  './patches/patch_2025-10-23_dashboard_drag_fix.js',
  './patches/patch_2025-10-23_actionbar_drag.js',
  './patches/patch_2025-10-23_calendar_contact_and_task.js',
  './patches/patch_2025-10-24_dashboard_drag_v2.js',
  './patches/patch_2025-10-24_quickadd_header_only.js',
  './ui/Toast.js',
  './ui/Confirm.js',
  './data/settings.js',
  './data/seed.js',
  './migrations.js',
  './templates.js',
  './filters.js',
  './state/selectionStore.js',
  './state/actionBarGuards.js',
  './ui/notifications_panel.js',
  './ui/action_bar.js',
  './ui/merge_modal.js',
  './debug/overlay.js',
  './quick_add.js',
  './doccenter_rules.js',
  './contacts.js',
  './partners.js',
  './partners_modal.js',
  './partners/list.js',
  './partners_merge.js',
  './partners_merge_orchestrator.js',
  './dash_range.js',
  './importer.js',
  './reports.js',
  './notifications.js',
  './calendar_impl.js',
  './calendar_actions.js',
  './calendar.js',
  './calendar_ics.js',
  './diagnostics_quiet.js',
  './doc/doc_center_enhancer.js',
  './email/templates_store.js',
  './importer_contacts.js',
  './importer_helpers.js',
  './importer_partners.js',
  './merge/merge_core.js',
  './notifications/notifier.js',
  './patches/loader.js',
  './selftest.js',
  './selftest_panel.js',
  '../seed_test_data.js',
  './snapshot.js',
  './ui/GhostButton.js',
  './ui/PrimaryButton.js',
  './ui/form_footer.js',
  './ui/header_toolbar.js',
  './ui/route_toast_sentinel.js',
  './ui/quick_add_unified.js',
  './ui/settings_form.js',
  './ui/strings.js',
  './util/strings.js',
  './ux/svg_sanitizer.js',
  './services/selection_adapter.js',
  './services/selection_fallback.js',
  './core/capabilities_probe.js',
  './patches/patch_2025-10-23_unify_quick_create.js',
  './patches/patch_2025-10-23_actionbar_drag.js',
  './patches/patch_2025-10-24_quickadd_header_only.js',
  './patches/patch_2025-10-23_calendar_contact_and_task.js'
];

export const SAFE_MODE = isSafeMode();

export const ACTIVE_PATCHES = SAFE_MODE ? [] : PATCHES;

const pickSpec = (list, suffix) => list.find((entry) => entry.endsWith(suffix)) ?? `./${suffix}`;

const REQUIRED_MODULES = [
  pickSpec(CORE, 'env.js'),
  pickSpec(CORE, 'db.js'),
  pickSpec(CORE, 'utils.js'),
  pickSpec(CORE, 'render.js'),
  pickSpec(PATCHES, 'ui/Toast.js'),
  pickSpec(PATCHES, 'ui/Confirm.js')
];

export const REQUIRED = new Set(REQUIRED_MODULES.map((spec) => {
  try {
    return normalizeModuleId(spec);
  } catch (_) {
    return spec;
  }
}));

export { normalizeModuleId, isSafeMode };
